python train.py --vocab_file ./vocab.korean_morp.list --bert_model_path ./ --dataset_path /workspace/mkdata/aiHub_cate/A_food --n_epochs 18
python train.py --vocab_file ./vocab.korean_morp.list --bert_model_path ./ --dataset_path /workspace/mkdata/aiHub_cate/B_clothes --n_epochs 18
python train.py --vocab_file ./vocab.korean_morp.list --bert_model_path ./ --dataset_path /workspace/mkdata/aiHub_cate/C_academy --n_epochs 18
python train.py --vocab_file ./vocab.korean_morp.list --bert_model_path ./ --dataset_path /workspace/mkdata/aiHub_cate/D_shop --n_epochs 18
python train.py --vocab_file ./vocab.korean_morp.list --bert_model_path ./ --dataset_path /workspace/mkdata/aiHub_cate/E_livingService --n_epochs 18
python train.py --vocab_file ./vocab.korean_morp.list --bert_model_path ./ --dataset_path /workspace/mkdata/aiHub_cate/F_cafe --n_epochs 18
python train.py --vocab_file ./vocab.korean_morp.list --bert_model_path ./ --dataset_path /workspace/mkdata/aiHub_cate/G_lodging --n_epochs 18
python train.py --vocab_file ./vocab.korean_morp.list --bert_model_path ./ --dataset_path /workspace/mkdata/aiHub_cate/H_tour --n_epochs 18
python train.py --vocab_file ./vocab.korean_morp.list --bert_model_path ./ --dataset_path /workspace/mkdata/aiHub_cate/J_civilService --n_epochs 18
